"""Add stats.id

Revision ID: 62009dbbb558
Revises: ed0954c682fe
Create Date: 2025-11-28 16:14:29.270348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62009dbbb558'
down_revision = 'ed0954c682fe'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('stats')

    op.create_table(
        'stats',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('year', sa.String(10), nullable=False),
        sa.Column('name', sa.Text, nullable=False),
        sa.Column('value', sa.Text, nullable=False, default=""),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')

    # ### end Alembic commands ###
